package GaT.validation;

import GaT.model.*;
import GaT.search.TerminalPositionDetector;

/**
 * STREAMLINED VALIDATION - Phase 3 Component 1
 *
 * ELIMINATES: Triple-redundant validation logic
 * PROVIDES: Fast path for generated moves, full validation only when needed
 * EXPECTED GAIN: 10-15% performance improvement
 */
public class StreamlinedValidation {

    // === VALIDATION MODES ===
    public enum ValidationMode {
        NONE,           // Trust completely (generated moves)
        BASIC,          // Minimal checks (internal moves)
        FULL,           // Complete validation (external input)
        DEBUG           // Extensive validation + logging
    }

    // === VALIDATION RESULTS (no exceptions in hot paths) ===
    public enum ValidationResult {
        VALID,
        INVALID_NULL_STATE,
        INVALID_NULL_MOVE,
        INVALID_OUT_OF_BOUNDS,
        INVALID_PIECE_MISMATCH,
        INVALID_ILLEGAL_MOVE,
        INVALID_GAME_OVER
    }

    // === FAST PATH VALIDATION (for generated moves) ===

    /**
     * Lightning-fast validation for moves generated by MoveGenerator
     * Assumes move structure is correct, only checks game state
     */
    public static ValidationResult validateFast(GameState state, Move move) {
        // Null checks (should never happen with generated moves)
        if (state == null) return ValidationResult.INVALID_NULL_STATE;
        if (move == null) return ValidationResult.INVALID_NULL_MOVE;

        // Basic bounds check (only validation needed for generated moves)
        if (move.from < 0 || move.from >= 49 || move.to < 0 || move.to >= 49) {
            return ValidationResult.INVALID_OUT_OF_BOUNDS;
        }

        return ValidationResult.VALID;
    }

    // === BASIC VALIDATION (for internal moves) ===

    /**
     * Basic validation for moves from internal sources
     * More thorough than fast path but still optimized
     */
    public static ValidationResult validateBasic(GameState state, Move move) {
        ValidationResult fastResult = validateFast(state, move);
        if (fastResult != ValidationResult.VALID) return fastResult;

        // Check if piece exists at source
        long fromBit = GameState.bit(move.from);
        boolean hasRedPiece = (state.redTowers & fromBit) != 0 || (state.redGuard & fromBit) != 0;
        boolean hasBluePiece = (state.blueTowers & fromBit) != 0 || (state.blueGuard & fromBit) != 0;

        if (!hasRedPiece && !hasBluePiece) {
            return ValidationResult.INVALID_PIECE_MISMATCH;
        }

        // Check turn consistency
        if (state.redToMove && !hasRedPiece) return ValidationResult.INVALID_PIECE_MISMATCH;
        if (!state.redToMove && !hasBluePiece) return ValidationResult.INVALID_PIECE_MISMATCH;

        return ValidationResult.VALID;
    }

    // === FULL VALIDATION (for external input) ===

    /**
     * Complete validation for moves from external sources (UI, network, etc.)
     */
    public static ValidationResult validateFull(GameState state, Move move) {
        ValidationResult basicResult = validateBasic(state, move);
        if (basicResult != ValidationResult.VALID) return basicResult;

        // Check if game is already over
        TerminalPositionDetector.TerminalType terminal = TerminalPositionDetector.detectTerminal(state);
        if (terminal != TerminalPositionDetector.TerminalType.NOT_TERMINAL) {
            return ValidationResult.INVALID_GAME_OVER;
        }

        // Check if move is actually legal by generating all legal moves
        // (Expensive operation - only for external input)
        try {
            java.util.List<Move> legalMoves = GaT.search.MoveGenerator.generateAllMoves(state);
            if (!legalMoves.contains(move)) {
                return ValidationResult.INVALID_ILLEGAL_MOVE;
            }
        } catch (Exception e) {
            return ValidationResult.INVALID_ILLEGAL_MOVE;
        }

        return ValidationResult.VALID;
    }

    // === SMART VALIDATION DISPATCHER ===

    /**
     * Automatically choose appropriate validation level
     */
    public static ValidationResult validateSmart(GameState state, Move move, ValidationMode mode) {
        switch (mode) {
            case NONE:
                return ValidationResult.VALID;
            case BASIC:
                return validateBasic(state, move);
            case FULL:
                return validateFull(state, move);
            case DEBUG:
                return validateWithLogging(state, move);
            default:
                return validateBasic(state, move);
        }
    }

    // === EXCEPTION-FREE MOVE MAKING ===

    /**
     * Make move with validation but no exceptions (returns null on failure)
     */
    public static GameState makeValidatedMove(GameState state, Move move, ValidationMode mode) {
        ValidationResult result = validateSmart(state, move, mode);
        if (result != ValidationResult.VALID) {
            return null; // No exception - just return null
        }

        try {
            return state.makeMove(move);
        } catch (Exception e) {
            return null; // Convert exception to null return
        }
    }

    // === BATCH VALIDATION (for move lists) ===

    /**
     * Validate entire move list efficiently
     */
    public static boolean validateMoveList(GameState state, java.util.List<Move> moves, ValidationMode mode) {
        if (moves == null || moves.isEmpty()) return true;

        for (Move move : moves) {
            ValidationResult result = validateSmart(state, move, mode);
            if (result != ValidationResult.VALID) {
                return false;
            }
        }
        return true;
    }

    // === DEBUG VALIDATION ===

    private static ValidationResult validateWithLogging(GameState state, Move move) {
        System.out.println("🔍 DEBUG VALIDATION: " + move);

        ValidationResult result = validateFull(state, move);
        System.out.println("   Result: " + result);

        if (result != ValidationResult.VALID) {
            System.out.println("   State: " + state.toFen());
        }

        return result;
    }

    // === PERFORMANCE VALIDATION ===

    /**
     * Get recommended validation mode based on performance requirements
     */
    public static ValidationMode getRecommendedMode(boolean isSearching, boolean isFromUI) {
        if (isSearching) {
            return ValidationMode.NONE; // Trust generated moves during search
        } else if (isFromUI) {
            return ValidationMode.FULL; // Validate user input thoroughly
        } else {
            return ValidationMode.BASIC; // Internal moves need basic validation
        }
    }

    // === INTEGRATION HELPERS ===

    /**
     * Convert validation result to boolean (for legacy compatibility)
     */
    public static boolean isValid(ValidationResult result) {
        return result == ValidationResult.VALID;
    }

    /**
     * Get human-readable error message
     */
    public static String getErrorMessage(ValidationResult result) {
        switch (result) {
            case VALID: return "Move is valid";
            case INVALID_NULL_STATE: return "Game state is null";
            case INVALID_NULL_MOVE: return "Move is null";
            case INVALID_OUT_OF_BOUNDS: return "Move coordinates out of bounds";
            case INVALID_PIECE_MISMATCH: return "No piece at source or wrong color";
            case INVALID_ILLEGAL_MOVE: return "Move is not legal";
            case INVALID_GAME_OVER: return "Game is already over";
            default: return "Unknown validation error";
        }
    }
}